
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'Missl_UAE'
version: '1.0.0'
config-version: 2

vars:
    project: Missl_UAE
    project_dataset: noted-computing-279322.halo_1_1_missluaetest
    
    Country: ('MissLUAE')

# This setting configures which "profile" dbt uses for this project.
profile: 'Missl_UAE'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  Missl_UAE:
  #give the project name used on the top
    Missl_UAE:
      +full_refresh: true
        # Applies to all files under models/example/
      Tables:
          materialized: table
      Views:
          materialized: view
          